button_option: stbc_button
comments: 0
late_load: 0
location: content
node_types:
  article: article
  blog: blog
  gallery: gallery
  news: news
  page: page
option_extras:
  'Google Plus One:plusone': 'Google Plus One:plusone'
  'Facebook Like:fblike': 'Facebook Like:fblike'
option_neworzero: 0
option_onhover: 1
option_shorten: 1
service_option: '"Facebook:facebook","Tweet:twitter","LinkedIn:linkedin","Email:email","ShareThis:sharethis","Pinterest:pinterest"'
twitter_handle: ''
twitter_recommends: ''
twitter_suffix: ''
webform_options: ''
weight: 10
widget_option: st_multi
cns:
  donotcopy: null
  hashaddress: null
sharethisnodes:
  article:
    full: full
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
    token: '0'
  page:
    full: full
    teaser: teaser
    rss: '0'
    search_index: '0'
    search_result: '0'
    token: '0'
  blog:
    full: full
    teaser: teaser
    rss: '0'
    search_index: '0'
    search_result: '0'
    token: '0'
  gallery:
    full: full
    teaser: teaser
    rss: '0'
    search_index: '0'
    search_result: '0'
    token: '0'
  news:
    full: full
    teaser: teaser
    rss: '0'
    search_index: '0'
    search_result: '0'
    token: '0'
_core:
  default_config_hash: OUePCWmQ_tUOCD4VF7-AP0maPJi2Y18f0JvNTgThhRQ
publisherID: dr-f7869c16-ef67-1f78-18bf-33f6aa882df4
callesi: '0'
